### ISSUE TITLE
Which name correspond to ProMP in the full_code branch?

### ISSUE THREAD

**Issue by NagisaZj** [jonasrothfuss/ProMP#12]
Hi. I am trying to reproduce the results about gradient variance comparison. I know from previous issues that the codes are in https://github.com/jonasrothfuss/ProMP/tree/full_code/experiments/gradient_variance. There seem to be three algorithms tested in run_sweep.py, with the names VPG, VPG_DICE and DICE, respectively. 

But in your paper, you show two curves: LVC and DICE, and I am confused about that. Does the DICE curve correspond to the mane 'DICE' in the script? Then which name does the curve LVC correspond to? Also, what does the third name correspond to?

**Comment by jonasrothfuss** [comment]
I think VPGMAML should corresponds to LVC.

**Comment by NagisaZj** [comment]
> I think VPGMAML should corresponds to LVC.

Thank you! Another minor question: can you provide the Doodad version you use? It seemed that the latest version of Doodad on Github does not work

**Comment by jonasrothfuss** [comment]
https://github.com/jonasrothfuss/doodad
