### ISSUE TITLE
Question about Figures in the paper and log files

### ISSUE THREAD

**Issue by rasoolfa** [jonasrothfuss/ProMP#5]
Hi,

Thanks for sharing this repo.

I was wondering which column(s) of progress.csv was used to plot Figure 2,3, and 7? Based on my understanding from the paper, I figure it is  "Step_1-AverageReturn", is it right? 

In addation, were log data for Figure 2,3 and 7 collected by running the followings? 
` python run_scripts/maml_run_mujoco.py` 
`python run_scripts/pro-mp_run_mujoco.py `

And finally, where were the 3 ranodm seeds?

That would be great if you please let me know about these.

Thanks.

**Comment by jonasrothfuss** [comment]
1) As far as I recall the plots were made with "Step_1-AverageReturn". In some environments two adaptation steps were necessary, then we used "Step_2-AverageReturn". See Appendix of the paper which environments these were.

2) Regarding the experiment scripts that were run to generate the respective data, check out our website:
https://sites.google.com/view/pro-mp/experiments

Also you can find all the csv files and more on the website.

3) As stated in the paper, there were at least 3 random seeds

**Comment by rasoolfa** [comment]
When I initially checked out your website, I was looking at the "master" branch, so didn't see the "experiments" folder. But once I switched to "full_code" branch, I saw all the codes. Thanks. 

Also, found out that you were using  [1, 2, 3] as the seed values.
