### ISSUE TITLE
Difference between maml and e-maml

### ISSUE THREAD

**Issue by hzyjerry** [jonasrothfuss/ProMP#8]
Hi, thanks for opensourcing the code!

I am wondering what's the difference between [e-maml](https://github.com/jonasrothfuss/ProMP/blob/master/run_scripts/e-maml_run_mujoco.py) and [maml](https://github.com/jonasrothfuss/ProMP/blob/master/run_scripts/maml_run_mujoco.py) code? A line-by-line comparison seems to suggest that they are identical.

Would appreciate your insights. Thanks!

**Comment by jonasrothfuss** [comment]
The only difference ist the exploration=True flag in the method arguments of TRPOMAML. If this flag is set to true, the "meta-exploration" term of E-MAML is added.
