### ISSUE TITLE
How to use your model?

### ISSUE THREAD

**Issue by cubicgate** [jonasrothfuss/ProMP#9]
Thanks for your code. After runinng the programs in run_scripts folder, we get "Training finished".
Could you tell me how to use the model created?

**Comment by jonasrothfuss** [comment]
In the full_code branch under experiment_utils, you can find the sim_policy.py script (https://github.com/jonasrothfuss/ProMP/blob/full_code/experiment_utils/sim_policy.py). That's what you need to run policy dumps generated during training.

**Comment by cubicgate** [comment]
Thanks!
